"""The single LLM seam. All model access goes through here (LiteLLM, Claude by default).

Pipeline code must never import an LLM SDK directly — call ``caption_image``. Generation is
image-first and vision-grounded (PRODUCT_SPEC §3): the chosen stock image is passed to the
model, which writes a bilingual (Hebrew-first) caption to match it. When no provider key is
configured the function returns a deterministic stub suggestion so the skeleton runs (and
tests pass) fully offline.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from pydantic import ValidationError

from app.config import Settings, get_settings
from app.schemas import PostSuggestion
from app.stock import load_image_b64

logger = logging.getLogger(__name__)


class CaptionError(Exception):
    """Raised when the LLM returns an unparseable or schema-invalid response."""


_SYSTEM_PROMPT = """\
You are CuteBot, an expert social-media copywriter for a single brand.
Write posts that sound exactly like the brand's own voice — never generic or corporate.
You must follow the brand's hard rules. Return ONLY valid JSON.
"""

_USER_TEMPLATE = """\
Here are the brand guidelines (the source of truth for voice, rules, and themes):

<brand_guidelines>
{brand}
</brand_guidelines>

The attached image is the post's visual. Write a caption grounded in what you actually see in
the image — never invent a different scene. Write the caption in native-quality Hebrew (the
primary language; this is a hard quality gate, not a translation) and in English, both in the
brand's voice and respecting every hard rule. Do NOT add any AI-disclosure or "generated by"
text — that is appended separately in code.

Return a JSON object of this exact shape:
{{"caption_he": "...", "caption_en": "...", "visual_concept": "...", "rationale": "..."}}

- caption_he: the Hebrew caption (primary language), grounded in the image.
- caption_en: the English caption, matching caption_he in meaning and voice.
- visual_concept: one sentence describing what the image actually shows.
- rationale: one sentence on why this fits the brand (for the human reviewer).
"""


def _provider_key() -> str | None:
    """The API key for the configured provider, or None if not set.

    LiteLLM reads keys from ``os.environ`` only — pydantic-settings loads them into the
    ``Settings`` object, not the environment — so we pass the key explicitly to
    ``acompletion`` rather than relying on env lookup.
    """
    s = get_settings()
    model = s.default_llm_model
    if model.startswith("anthropic/"):
        return s.anthropic_api_key or None
    if model.startswith("openai/") or model.startswith("gpt"):
        return s.openai_api_key or None
    return None


def _has_provider_key() -> bool:
    s = get_settings()
    model = s.default_llm_model
    if model.startswith(("anthropic/", "openai/", "gpt")):
        return _provider_key() is not None
    # Unknown provider — assume the env is configured for it.
    return True


def _stub_suggestion(image_path: Path) -> PostSuggestion:
    return PostSuggestion(
        caption_he=f"[סטאב] קבעו ANTHROPIC_API_KEY כדי לכתוב כיתוב אמיתי ל-{image_path.name}.",
        caption_en=f"[stub caption for {image_path.name}] set ANTHROPIC_API_KEY for a real one.",
        visual_concept=f"[stub visual] referencing {image_path.name}.",
        rationale="Offline stub — no LLM provider key configured.",
    )


async def caption_image(brand: str, image_path: Path, settings: Settings) -> PostSuggestion:
    """Caption ``image_path`` (vision) in the brand's voice. One call per image."""
    if not _has_provider_key():
        logger.warning("No LLM provider key configured — returning a stub suggestion.")
        return _stub_suggestion(image_path)

    # Imported lazily so the package imports cleanly without litellm installed in
    # minimal environments, and so the offline path never touches the network.
    import litellm

    mime_type, b64 = load_image_b64(image_path)
    messages = [
        {"role": "system", "content": _SYSTEM_PROMPT},
        {
            "role": "user",
            "content": [
                {"type": "text", "text": _USER_TEMPLATE.format(brand=brand)},
                {"type": "image_url", "image_url": {"url": f"data:{mime_type};base64,{b64}"}},
            ],
        },
    ]
    response = await litellm.acompletion(
        model=settings.default_llm_model,
        messages=messages,
        response_format={"type": "json_object"},
        max_tokens=settings.llm_max_tokens,
        timeout=settings.llm_timeout_s,
        num_retries=settings.llm_num_retries,
        # LiteLLM only reads keys from os.environ; pass explicitly since pydantic-settings
        # loads them into Settings, not the environment.
        api_key=_provider_key(),
    )
    content = response["choices"][0]["message"]["content"]
    try:
        data = json.loads(content)
        return PostSuggestion.model_validate(data)
    except (json.JSONDecodeError, ValidationError) as exc:
        logger.error("LLM returned invalid response for %s: %.200s", image_path.name, content)
        raise CaptionError(str(exc)) from exc
