"""The single LLM seam. All model access goes through here (LiteLLM, Claude by default).

Pipeline code must never import an LLM SDK directly — call ``caption_image``. Generation is
image-first and vision-grounded (PRODUCT_SPEC §3): the chosen stock image is passed to the
model, which writes a bilingual (Hebrew-first) caption to match it. When no provider key is
configured the function returns a deterministic stub suggestion so the skeleton runs (and
tests pass) fully offline.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from pydantic import ValidationError

from app.config import Settings
from app.learning import LearningContext, render
from app.schemas import BrandProposal, PostSuggestion
from app.stock import load_image_b64

logger = logging.getLogger(__name__)


class CaptionError(Exception):
    """Raised when the LLM returns an unparseable or schema-invalid response."""


_SYSTEM_PROMPT = """\
You are CuteBot, an expert social-media copywriter for a single brand.
Write posts that sound exactly like the brand's own voice — never generic or corporate.
You must follow the brand's hard rules. Return ONLY valid JSON.
"""

_USER_TEMPLATE = """\
Here are the brand guidelines (the source of truth for voice, rules, and themes):

<brand_guidelines>
{brand}
</brand_guidelines>
{learning}
The attached image is the post's visual. Write a caption grounded in what you actually see in
the image — never invent a different scene. Write the caption in native-quality Hebrew (the
primary language; this is a hard quality gate, not a translation) and in English, both in the
brand's voice and respecting every hard rule. Do NOT add any AI-disclosure or "generated by"
text — that is appended separately in code.

Return a JSON object of this exact shape:
{{"caption_he": "...", "caption_en": "...", "visual_concept": "...", "rationale": "..."}}

- caption_he: the Hebrew caption (primary language), grounded in the image.
- caption_en: the English caption, matching caption_he in meaning and voice.
- visual_concept: one sentence describing what the image actually shows.
- rationale: one sentence on why this fits the brand (for the human reviewer).
"""


def _user_prompt(brand: str, context: LearningContext | None) -> str:
    block = render(context)
    return _USER_TEMPLATE.format(brand=brand, learning=f"\n{block}\n" if block else "")


def _provider_key(s: Settings) -> str | None:
    """The API key for ``s.default_llm_model``'s provider, or None if not set.

    LiteLLM reads keys from ``os.environ`` only — pydantic-settings loads them into the
    ``Settings`` object, not the environment — so we pass the key explicitly to
    ``acompletion`` rather than relying on env lookup. Keyed off the *passed* settings so
    callers (e.g. scripts/eval_models.py) can sweep models without touching the global.
    """
    model = s.default_llm_model
    if model.startswith("anthropic/"):
        return s.anthropic_api_key or None
    if model.startswith("openai/") or model.startswith("gpt"):
        return s.openai_api_key or None
    return None


def _has_provider_key(s: Settings) -> bool:
    if s.default_llm_model.startswith(("anthropic/", "openai/", "gpt")):
        return _provider_key(s) is not None
    # Unknown provider — assume the env is configured for it.
    return True


def _strip_fences(text: str) -> str:
    """A fenced code block (```json ... ```) → the inner JSON; anything else passes through."""
    t = text.strip()
    if t.startswith("```"):
        t = t.split("\n", 1)[1] if "\n" in t else ""
        t = t.rsplit("```", 1)[0]
    return t.strip()


def _unwrap_json_envelope(data: object) -> object:
    """Some models (seen with Opus under response_format=json_object) wrap the object
    in a single-key ``{"json": {...}}`` envelope. Unwrap it so validation sees the
    flat fields; leave anything else untouched."""
    if isinstance(data, dict) and list(data) == ["json"] and isinstance(data["json"], dict):
        return data["json"]
    return data


def _stub_suggestion(image_path: Path) -> PostSuggestion:
    return PostSuggestion(
        caption_he=f"[סטאב] קבעו ANTHROPIC_API_KEY כדי לכתוב כיתוב אמיתי ל-{image_path.name}.",
        caption_en=f"[stub caption for {image_path.name}] set ANTHROPIC_API_KEY for a real one.",
        visual_concept=f"[stub visual] referencing {image_path.name}.",
        rationale="Offline stub — no LLM provider key configured.",
    )


async def _complete(
    messages: list[dict[str, Any]], settings: Settings, min_tokens: int = 0
) -> Any:
    """One LiteLLM completion with the provider quirks applied (token cap, effort, JSON mode).

    ``min_tokens`` raises the output cap for calls whose answer is known to be long (the
    distillation returns a whole brand file).
    """
    # Imported lazily so the package imports cleanly without litellm installed in
    # minimal environments, and so the offline path never touches the network.
    import litellm

    # OpenAI models (GPT-5+/GPT-6/o-series) reject the legacy max_tokens and want
    # max_completion_tokens; everything else (incl. Claude) uses max_tokens.
    is_openai = settings.default_llm_model.startswith("openai/")
    effort = settings.llm_reasoning_effort if is_openai else ""
    cap = max(settings.llm_max_tokens, min_tokens)
    if effort and effort != "none":
        # reasoning tokens count against the completion cap — a tight cap returns
        # empty content instead of a caption.
        cap = max(cap, 8000)
    token_cap = {"max_completion_tokens": cap} if is_openai else {"max_tokens": cap}
    extra = {"reasoning_effort": effort} if effort else {}
    # LiteLLM implements json_object for Anthropic by forcing a tool call, which
    # Claude 5.5+ rejects (400 "tool_choice: type any not supported"). The prompt
    # already demands bare JSON, so Claude gets no response_format; fences are
    # stripped below just in case.
    fmt = (
        {}
        if settings.default_llm_model.startswith("anthropic/")
        else {"response_format": {"type": "json_object"}}
    )
    return await litellm.acompletion(
        model=settings.default_llm_model,
        messages=messages,
        **fmt,
        **token_cap,
        **extra,
        timeout=settings.llm_timeout_s,
        num_retries=settings.llm_num_retries,
        # LiteLLM only reads keys from os.environ; pass explicitly since pydantic-settings
        # loads them into Settings, not the environment.
        api_key=_provider_key(settings),
    )


async def caption_image(
    brand: str,
    image_path: Path,
    settings: Settings,
    context: LearningContext | None = None,
) -> PostSuggestion:
    """Caption ``image_path`` (vision) in the brand's voice. One call per image.

    ``context`` (M8) adds the owner's approved posts / reject hints / recent posts to the
    prompt; ``None`` or empty renders exactly the pre-M8 prompt.
    """
    if not _has_provider_key(settings):
        logger.warning("No LLM provider key configured — returning a stub suggestion.")
        return _stub_suggestion(image_path)

    mime_type, b64 = load_image_b64(image_path)
    messages: list[dict[str, Any]] = [
        {"role": "system", "content": _SYSTEM_PROMPT},
        {
            "role": "user",
            "content": [
                {"type": "text", "text": _user_prompt(brand, context)},
                {"type": "image_url", "image_url": {"url": f"data:{mime_type};base64,{b64}"}},
            ],
        },
    ]
    response = await _complete(messages, settings)
    content = _strip_fences(response["choices"][0]["message"]["content"])
    try:
        data = json.loads(content)
        data = _unwrap_json_envelope(data)
        sug = PostSuggestion.model_validate(data)
    except (json.JSONDecodeError, ValidationError) as exc:
        logger.error("LLM returned invalid response for %s: %.200s", image_path.name, content)
        raise CaptionError(str(exc)) from exc
    usage = getattr(response, "usage", None)
    if usage is not None:  # for the eval's cost column; never stored on the post
        sug.tokens_in = getattr(usage, "prompt_tokens", None)
        sug.tokens_out = getattr(usage, "completion_tokens", None)
    return sug


_DISTILL_PROMPT = """\
Below are the brand guidelines (brand.md) and the owner's recent feedback on generated posts:
approved examples, hand-corrected captions, and reasons posts were rejected.

<brand_guidelines>
{brand}
</brand_guidelines>

<recent_feedback>
{evidence}
</recent_feedback>

Propose a minimal revision of brand.md that captures what the feedback teaches — voice,
hard rules, phrasing the owner corrects. Change only what the evidence supports; keep every
existing hard rule and the file's structure and language. If nothing is worth changing,
return the file unchanged.

Return ONLY a JSON object: {{"new_brand": "<the complete revised brand.md>",
"rationale": "<one paragraph: what changed and which feedback justifies it>"}}
"""


async def distill_brand(brand: str, evidence: str, settings: Settings) -> BrandProposal:
    """Ask the model for a revised ``brand.md`` given recent feedback (M8.4, owner-triggered)."""
    if not _has_provider_key(settings):
        raise CaptionError("No LLM provider key configured — cannot distill.")
    response = await _complete(
        [
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": _DISTILL_PROMPT.format(brand=brand, evidence=evidence)},
        ],
        settings,
        # the answer embeds the complete revised brand.md (~10 KB of Hebrew) plus thinking
        min_tokens=16000,
    )
    content = _strip_fences(response["choices"][0]["message"]["content"])
    try:
        return BrandProposal.model_validate(_unwrap_json_envelope(json.loads(content)))
    except (json.JSONDecodeError, ValidationError) as exc:
        logger.error("LLM returned invalid distillation: %.200s", content)
        raise CaptionError(str(exc)) from exc
